### ISSUE TITLE
ユーザーのログイン画面の実装

### ISSUE THREAD

**Issue by gonta1026** [gonta1026/manemagi_front#2]
## タスク

- ユーザーの新規登録画面を実装

## 備考
- 新規登録とほぼ同様に作ってください。
- formのstate管理にformikを使ってください。
-ブランチ は`feature-2-user_login`でお願いします。

# エンドポイント

`~~~/api/auth/sign_in`

下記のような構造のリクエストを送ってください。

```
{
    "email": "tesazzzzaalas0dd01@gmail.com",
    "password": "11111111"
}
```
## 参考画像

**Comment by fukadashigeru** [comment]
- [x] 下記をポストマンにimport
https://toraseminar.slack.com/files/U018R4FLDCZ/F026R5JE8GN/manamagi_api.postman_collection.json
- [x] env.localをルートに配置
- [x] Sequel Proで繋ぐ

**Comment by gonta1026** [comment]
@fukadashigeru 
あ、importです

**Comment by gonta1026** [comment]
@fukadashigeru 
ここのimportて書いているところでいけます？
![スクリーンショット 2021-07-02 23 09 42](https://user-images.githubusercontent.com/45672476/124287282-cca0eb80-db8a-11eb-8d9e-4d10c4df3c29.png)

**Comment by fukadashigeru** [comment]
@gonta1026
できたっす！ 
![image](https://user-images.githubusercontent.com/45095615/124287982-9b74eb00-db8b-11eb-8e21-008dcb9a9070.png)

みんなは分かってると思うけど共有
![dee85a9bc2492f7f5c7bf7f7b00e4f05](https://user-images.githubusercontent.com/45095615/124288286-f9093780-db8b-11eb-89a5-f8ae18135a7c.gif)

**Comment by gonta1026** [comment]
おー！さすが！

**Comment by gonta1026** [comment]
@fukadashigeru 
あ、個別でDB情報送ります！

**Comment by gonta1026** [comment]
ログインを成功させて`localStorage`にtoken等を保存をするところまで確認お願いします

**Comment by gonta1026** [comment]
@fukadashigeru
