### ISSUE TITLE
ヘッダーとドロワーメニューのコンポーネントを実装

### ISSUE THREAD

**Issue by gonta1026** [gonta1026/manemagi_front#3]
# タスク
- ヘッダーコンポーネントとドロワーメニューを実装

# 備考
- Materialーuiの『App Bar』を使えばいいと思います。
- スマホでうまく表示をされてPCでも最低限見た目が崩れないようにお願いします・
- ブランチはdevelopから`feature-base_header`で切って作業をし、developにむけてプルリクエストを作成してください

# 参考
- https://material-ui.com/components/drawers/#temporary-drawer 
- https://material-ui.com/components/app-bar/#simple-app-bar

**Comment by ayataka19** [comment]
コンポーネントの細かいデザインやメニューの種類などはこちらで仮決めしておいて、後から必要に応じて変更する形でよろしいでしょうか？現時点で何か決まっているものがあれば教えてください！

**Comment by ayataka19** [comment]
ヘッダーとドロワーメニューは、全ての画面で表示する（src/pages/index.tsxにimportする？）で合ってますか？

**Comment by gonta1026** [comment]
> コンポーネントの細かいデザインやメニューの種類などはこちらで仮決めしておいて、後から必要に応じて変更する形でよろしいでしょうか？現時点で何か決まっているものがあれば教えてください！

正直デザインに細かいこだわりはなく、機能がみたせればいいくらいな感じです！
なので一旦作ってもらって変更をお願いして調整していくイメージでした！

> ヘッダーとドロワーメニューは、全ての画面で表示する（src/pages/index.tsxにimportする？）で合ってますか？

新規登録、ログインの画面では使用しないつもりですがもしかしたら使うかもしれないです！

ごめんなさい！なお、こちら自分の方で一旦作成させていただきました💦
なお、下記にようなイメージでお願いする感じでした！

https://gyazo.com/ac9c4354af770f075dfddd2b00ce5069

**Comment by gonta1026** [comment]
@ayataka19

**Comment by gonta1026** [comment]
対応済みのためクローズ
